caixas/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url


urlpatterns = patterns('caixas.views',
    url(r'^adicionar/$', 'caixaAdicionar'),
    url(r'^editar/(?P<pk>\d+)/$', 'caixaEditar'),
    url(r'^salvar/$', 'caixaSalvar'),
    url(r'^pesquisar/$', 'caixaPesquisar'),
    url(r'^excluir/(?P<pk>\d+)/$', 'caixaExcluir'),
    url(r'^$', 'caixaListar'),

    url(r'^fluxo/$', 'caixaFluxo'),
    url(r'^fluxo/busca/$', 'fluxodecaixa'),
    url(r'^fluxo/relatorio/$', 'fluxodecaixa'),
)

projetoFP/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'pessoas.views.index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pessoas/', include('pessoas.urlsPessoas')),
    url(r'^caixas/', include('caixas.urls')),
)

caixas/models.py
# coding: utf-8
from django.db import models
from pessoas.models import Pessoa

class Caixa(models.Model):
    pessoa = models.ForeignKey(Pessoa)
    #E = Entrada / S = Saida
    tipo = models.CharField(db_index=True, max_length='1', blank=False, null=False)
    descricao = models.CharField(db_index=True, max_length='200', blank=False, null=False)
    valor = models.DecimalField(max_digits=13, decimal_places=2, default=0)
    pagseguro = models.CharField(max_length='300', blank=True)
    data = models.DateTimeField(db_index=True, auto_now=False, auto_now_add=True)

core/models.py
from django.db import models

# Create your models here.

pessoas/models.py
from django.db import models

class Pessoa(models.Model):
    nome = models.CharField(max_length='100',
        blank=False,
        null=False)

    email = models.CharField(max_length='100',
        blank=True,
        null=True)

    telefone = models.CharField(max_length='20',
        blank=True,
        null=True)

    logradouro = models.CharField(max_length='200',
        blank=True,
        null=True)

caixas/views.py
# coding: utf-8
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.db.models import Q
from .models import Caixa
from pessoas.models import Pessoa
from datetime import datetime



def index(request):
    return render(request, 'index.html')


def caixaListar(request):
    caixas = Caixa.objects.all()[0:10]
    pessoas = Pessoa.objects.all()[0:10]

    return render(request, 'caixas/listaCaixas.html', {'caixas': caixas, 'pessoas': pessoas})


def caixaAdicionar(request):
    pessoas = Pessoa.objects.all()
    return render(request, 'caixas/formCaixas.html', {'pessoas': pessoas})



def caixaSalvar(request):
    if request.method == 'POST':
        codigo = request.POST.get('codigo', '0')

        try:
            caixa = Caixa.objects.get(pk=codigo)
        except:
            caixa = Caixa()

        caixa.pessoa_id = request.POST.get('pessoa_id', '0')
        caixa.pessoa = Pessoa.objects.get(pk=request.POST.get('pessoa','1'))
        caixa.tipo = request.POST.get('tipo', '').upper()
        caixa.descricao = request.POST.get('descricao', 'CONTA SEM DESCRIÇÃO').upper()
        caixa.valor = request.POST.get('valor', '0.00').replace(',','.')
        caixa.pagseguro = request.POST.get('pagseguro', '').upper()
        caixa.data = request.POST.get(('data', ''), '%d/%m/%Y %H:%M:%S')

        caixa.save()
    return HttpResponseRedirect('/caixas/')


def caixaPesquisar(request):
    if request.method == 'POST':
        textoBusca = request.POST.get('textoBusca', 'TUDO').upper()

        try:
            if textoBusca == 'TUDO':
                caixas = Caixa.objects.all()
            else:
                caixas = Caixa.objects.filter(
                    (Q(tipo__contains=textoBusca) |
                    Q(descricao__contains=textoBusca) |
                    Q(valor__contains=textoBusca) |
                    Q(pagseguro__contains=textoBusca) |
                    Q(data__contains=textoBusca))).order_by('-tipo')
        except:
            caixas = []

        return render(request, 'caixas/listaCaixas.html', {'caixas': caixas,
                      'textoBusca': textoBusca})


def caixaEditar(request, pk=0):
    try:
        caixa = Caixa.objects.get(pk=pk)
    except:
        return HttpResponseRedirect('/caixas/')

    return render(request, 'caixas/formCaixas.html', {'caixa': caixa})


def caixaExcluir(request, pk=0):
    try:
        caixa = Caixa.objects.get(pk=pk)
        caixa.delete()
        return HttpResponseRedirect('/caixas/')
    except:
        return HttpResponseRedirect('/caixas/')


def caixaFluxo(request):
    caixas = []
    return render(request, 'caixas/fluxo_de_caixa.html', {'caixas': caixas})


def fluxodecaixa(request):
    if request.method == 'POST':
        dataInicial = request.POST.get('dataInicial', '')
        dataFinal = request.POST.get('dataFinal', '')

        try:
            dataInicial = datetime.strptime(dataInicial, '%d/%m/%y')
            dataFinal = datetime.strptime(dataFinal, '%d/%m/%y')
            caixas = Caixa.objects.filter(data_ranger=(dataInicial, dataFinal))
        except:
            caixas = []

        total = 0
        for caixa in caixas:
            if caixa.tipo == 'E':
                total = total + caixa.valor
            else:
                total = total - caixa.valor

        return render(request, 'caixas/fluxo_de_caixa.html',
                {'caixas':caixas, 'total':total, 'dataInicial':dataInicial,
                'dataFinal':dataFinal})

    return render(request, 'caixas/fluxo_de_caixa.html')

core/views.py
from django.shortcuts import render

# Create your views here.

pessoas/views.py
# coding: utf-8
from django.shortcuts import render, HttpResponseRedirect
from django.db.models import Q
from pessoas.models import Pessoa

def index(request):
    return render(request, 'index.html')

def pessoaListar(request):
    pessoas = Pessoa.objects.all()[0:10]

    # TESTE LOCAL PARA VERIFICAR SE A TABELA ESTA LISTANDO
    #pessoas = []
    #pessoas.append(Pessoa(nome='NOME1', email='MAIL', telefone='TELEFONE'))
    #pessoas.append(Pessoa(nome='NOME2'))

    return render(request, 'pessoas/listaPessoas.html', {'pessoas': pessoas})


def pessoaAdicionar(request):
    return render(request, 'pessoas/formPessoas.html')

def pessoaSalvar(request):
    if request.method == 'POST':
        codigo = request.POST.get('codigo', '0')

        try:
            pessoa = Pessoa.objects.get(pk=codigo)
        except:
            pessoa = Pessoa()

        pessoa.nome = request.POST.get('nome', '').upper()
        pessoa.email = request.POST.get('email', '').upper()
        pessoa.telefone = request.POST.get('telefone', '(00) 0-0000-0000').upper()
        pessoa.logradouro = request.POST.get('logradouro', '').upper()

        pessoa.save()
    return HttpResponseRedirect('/pessoas/')

def pessoaPesquisar(request):
    if request.method == 'POST':
        textoBusca = request.POST.get('textoBusca', 'TUDO').upper()

        try:
            if textoBusca == 'TUDO':
                pessoas = Pessoa.objects.all()
            else:
                pessoas = Pessoa.objects.filter(
                    (Q(nome__contains=textoBusca) |
                    Q(email__contains=textoBusca) |
                    Q(telefone__contains=textoBusca) |
                    Q(logradouro__contains=textoBusca))).order_by('-nome')  #BUSCA POR NOME OU EMAIL OU TELEFONE OU LOGRADOURO... E É ORDENADO POR NOME.
        except:
            pessoas = []

        return render(request, 'pessoas/listaPessoas.html', {'pessoas': pessoas, 'textoBusca': textoBusca})

def pessoaEditar(request, pk=0):
    try:
        pessoa = Pessoa.objects.get(pk=pk)
    except:
        return HttpResponseRedirect('/pessoas/')

    return render(request, 'pessoas/formPessoas.html', {'pessoa': pessoa})

def pessoaExcluir(request, pk=0):
    try:
        pessoa = Pessoa.objects.get(pk=pk)
        pessoa.delete()
        return HttpResponseRedirect('/pessoas/')
    except:
        return HttpResponseRedirect('/pessoas/')

core/templates/base.html
{% load staticfiles %} <!-- PARA USAR O CAMINHO PADRAO STATIC_URL -->

<!DOCTYPE html>
<html lang="pt_BR">
<head>
    <meta charset="utf-8">

    <title>{% block titulo %}{% endblock titulo %} - Financeiro Pessoal</title>

    <!-- CSS -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/jasny-bootstrap.min.css' %}" rel="stylesheet">
    <!-- FIM CSS -->

</head>

<body>
    <!-- MENU -->
    <nav class="navbar navbar" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#IDnavbar">
            <span class="sr-only">Menu Mobile</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Financeiro Pessoal</a>
    </div>

    <div class="collapse navbar-collapse" id="IDnavbar">
      <ul class="nav navbar-nav">
        <li><a href="/pessoas/"> <spam class="glyphicon glyphicon-user"></spam> Pessoas</a></li>
        <li><a href="/caixas/"> <spam class="glyphicon glyphicon-inbox"></spam> Contas</a></li>
        <li><a href="caixas/fluxo/"> <spam class="glyphicon glyphicon-stats"></spam> Fluxo de Caixa</a></li>
    </ul>
</div>
</div>
</nav>

<!-- FIM MENU -->
<br />
<hr>
<div class="container">
  <!-- CONTEUDO -->
  {% block conteudo %}{% endblock conteudo %}
  <!-- FIM CONTEUDO -->
</div>
<hr>

<!-- RODAPE -->
<footer>
  <div align="center">&copy; Lucas Alves Ferreira</div>
</footer>
<!-- FIM RODAPE -->

<!-- JavaScript -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/core.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jasny-bootstrap.min.js' %}"></script>
<!-- FIM JavaScript -->

</body>
</html>

core/templates/caixas/fluxo_de_caixa.html
{% extends 'base.html' %}

{% block titulo %}Fluxo de Caixas{% endblock titulo %}

{% block conteudo %}
<h4>
  <div align="center">
    <form role="form" method="POST" action="/caixas/fluxo/busca/">
      {% csrf_token %}
      <div class="form-group">
        <div class="row">

          <div class="col-md-6">
            <p class="help-bloxk">Data Inicial</p>
            <input type="text" class="form-control" id="dataInicial" name="dataInicial" value="{{ dataInicial|date:"d/m/y" }}" placeholder="01/01/2014">
          </div>

          <div class="col-md-6">
            <p class="help-bloxk">Data Final</p>
            <input type="text" class="form-control" id="dataFinal" name="dataFinal" value="{{ dataFinal|date:"d/m/y" }}" placeholder="01/01/2014">
          </div>
        </div>


        <div></div>

        <div class="col-6" align="center">
          <button type="submit" class="btn btn-primary">Pesquisar <span class="glyphicon glyphicon-search"></span></button>
        </div>

      </div>
    </form>

  </div>
  <hr>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Tipo</th>
          <th>Descrição</th>
          <th>Valor</th>
          <th>PagSeguro</th>
          <th>Data</th>
        </tr>
      </thead>
      <tbody>
        {% for caixa in caixas %}
        <tr>
          <td>{{ caixa.pessoa.nome }}</td>
          <td>{{ caixa.tipo }}</td>
          <td><a href="/caixas/editar/{{ caixa.pk }}">{{ caixa.descricao }}</a></td>
          <td>{{ caixa.valor }}</td>
          <td>{{ caixa.pagseguro }}</td>
          <td>{{ caixa.data|date}}</td>
        </tr>
        {% endfor %}
        <tr>
          <td><b>TOTAL:</b></td>
          <td><b>{{ total }}</b></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
    </table>
  </div><!-- FIM TABELA -->

  {% endblock conteudo %}

core/templates/caixas/formCaixas.html
{% extends 'base.html' %}

{% block titulo %}Formulário de Contas{% endblock titulo %}

{% block conteudo %}
<script type="text/javascript">
$(function() {
    $('#datetimepicker1').datetimepicker({
      language: 'pt-BR'
  });
});
</script>
<form class="form-horizontal" action="/caixas/salvar/" method="POST" role="form">
    {% csrf_token %}

    <input type="hidden" id="codigo" name="codigo" value="{{ caixa.pk|default_if_none:'0' }}">

    <input type="hidden" id="pessoa_id" name="pessoa_id" value="{{ 1 }}">
    <div class="form-group">
        <label for="tipo" class="col-sm-2 control-label">Tipo</label>
        <div class="col-sm-4">
            <select class="form-control" name="tipo" id="pessoa_id" >
                <option value="E">SELECIONE CAIXA ENTRADA OU SAÍDA</option>
                <option {% if caixa.tipo == 'E' %} selected="selected" {% endif %} value="E">ENTRADA</option>
                <option {% if caixa.tipo == 'S' %} selected="selected" {% endif %} value="S">SAÍDA</option>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label for="id_descricao" class="col-sm-2 control-label">Descrição</label>
        <div class="col-sm-10">
            <input name="descricao" id="id_descricao" value="{{ caixa.descricao }}" type="text" class="form-control" placeholder="Descrição da conta...">
        </div>
    </div>

    <div class="form-group">
        <label for="id_valor" class="col-sm-2 control-label">Valor</label>
        <div class="col-sm-10">
            <input name="valor" id="id_valor" value="{{ caixa.valor }}" type="text" class="form-control" placeholder="0.00">
        </div>
    </div>

    <div class="form-group">
        <label for="id_pagseguro" class="col-sm-2 control-label">PagSeguro</label>
        <div class="col-sm-10">
            <input name="pagseguro" id="id_pagseguro" value="{{ caixa.pagseguro }}" type="text" class="form-control">
        </div>
    </div>
    <hr>

    <div align="center">
        <button type="submit" class="btn btn-success">Salvar Registro</button>
        {% if caixa.pk > 0 %}
        <a class="btn btn-danger" href="/caixas/excluir/{{ caixa.pk }}/">Excluir</a>
        {% endif %}
    </div>
</form>
{% endblock conteudo %}

core/templates/caixas/listaCaixas.html
{% extends 'base.html' %}

{% block titulo %}Caixas{% endblock titulo %}

{% block conteudo %}
<div align="center">
  <form role="form" method="POST" action="/caixas/pesquisar/">
    {% csrf_token %}
    <div class="form-group">
      <div class="row">
        <div class="col-md-10">
          <input type="text" class="form-control" id="textoBusca" name="textoBusca" value="{{ textoBusca }}" placeholder="Digite um texto para a busca...">
        </div>
        <div class="col-md-2" align="center">
          <button type="submit" class="btn btn-primary">Pesquisar <span class="glyphicon glyphicon-search"></span></button>
        </div>
      </div>
    </div>
  </form>

  <a href="/caixas/adicionar/" class="btn btn-warning">Cadastra Contas</a>

</div>
<hr>
<div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Tipo</th>
            <th>Descrição</th>
            <th>Valor</th>
            <th>PagSeguro</th>
            <th>Data</th>
          </tr>
        </thead>
        <tbody>
        {% for caixa in caixas %}
          <tr>
            <td>{{ caixa.pessoa.nome }}</td>
            <td>{{ caixa.tipo }}</td>
            <td><a href="/caixas/editar/{{ caixa.pk }}">{{ caixa.descricao }}</a></td>
            <td>{{ caixa.valor }}</td>
            <td>{{ caixa.pagseguro }}</td>
            <td>{{ caixa.data|date:"d/m/Y" }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
</div><!-- FIM TABELA -->

{% endblock conteudo %}

core/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block titulo %}Principal{% endblock titulo %}

{% block conteudo %}
	<div class="col-sm-6" align="center">
    	<img class="img-responsive" src="{% static 'logo/logo_G.png' %}">
            </div>
            <div class="col-sm-6" align="center">
            	<h2>Sistema FP</h2>
            	Um projeto legal para você aprender Python & Django na prática! Criamos um Financeiro Pessoal para entendermos como funciona as rotinas e todo o eco-sistema da internet usando essa tecnologia. <br />O código desse projeto encontra-se no <a href="https://github.com/lucasaf/projetoFP" target="_blank">Github</a> para você estudar à vontade!
            </div>
{%endblock conteudo %}

core/templates/pessoas/formPessoas.html
{% extends 'base.html' %}

{% block titulo %}Formulário da Pessoa{% endblock titulo %}

{% block conteudo %}
<form class="form-horizontal" action="/pessoas/salvar/" method="POST" role="form">{% csrf_token %}

    <input type="hidden" id="codigo" name="codigo" value="{{ pessoa.pk|default_if_none:'0' }}">

    <div class="form-group">
        <label for="idNome" class="col-sm-2 control-label">Nome</label>
        <div class="col-sm-10">
            <input name="nome" id="idNome" value="{{ pessoa.nome }}" type="text" class="form-control"  placeholder="Nome Completo...">
        </div>
    </div>

    <div class="form-group">
        <label for="idLogradouro" class="col-sm-2 control-label">Logradouro</label>
        <div class="col-sm-10">
            <input name="logradouro" id="idLogradouro" value="{{ pessoa.logradouro|default_if_none:'' }}" type="text" class="form-control"  placeholder="Rua, Número, Bairro e etc...">
        </div>
    </div>

    <div class="form-group">
        <label for="idTelefone" class="col-sm-2 control-label">Contatos</label>
            <div class="col-sm-5">
                <input name="telefone" id="idTelefone" value="{{ pessoa.telefone|default_if_none:'' }}" type="text" class="form-control"  placeholder="(00) 0-0000-0000" data-mask="(99) 9-9999-9999">
            </div>
            <div class="col-sm-5">
                <input name="email" id="idEmail" value="{{ pessoa.email|default_if_none:'' }}" type="email" class="form-control" placeholder="nome@dominio.com">
            </div>
    </div>

    <hr>

    <div align="center">
        <button type="submit" class="btn btn-success">Salvar Registro</button>
        {% if pessoa.pk > 0 %}
        <a class="btn btn-danger" href="/pessoas/excluir/{{ pessoa.pk }}/">Excluir</a>
        {% endif %}
    </div>
</form>
{% endblock conteudo %}

core/templates/pessoas/listaPessoas.html
{% extends 'base.html' %}

{% block titulo %}Pessoas{% endblock titulo %}

{% block conteudo %}
<div align="center"> 
  <form role="form" method="POST" action="/pessoas/pesquisar/">{% csrf_token %}
    <div class="form-group">
      <div class="row">
        <div class="col-md-10">
          <input type="text" class="form-control" id="textoBusca" name="textoBusca" value="{{ textoBusca }}" placeholder="Digite um texto para a busca...">
        </div>
        <div class="col-md-2" align="center">
          <button type="submit" class="btn btn-primary">Pesquisar <span class="glyphicon glyphicon-search"></span></button>
        </div>
      </div>
    </div>  
  </form>
  
  <a href="/pessoas/adicionar/" class="btn btn-warning">Cadastra Pessoa</a>

</div>
<hr>
<div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Nome</th>
            <th>E-Mail</th>
            <th>Telefone</th>
          </tr>
        </thead>
        <tbody>
        {% for pessoa in pessoas %}
          <tr>
            <td><a href="/pessoas/editar/{{ pessoa.pk }}">{{ pessoa.nome }}</a></td>
            <td>{{ pessoa.email }}</td>
            <td>{{ pessoa.telefone }}</td>
          </tr>
        {% endfor %}  
        </tbody>
      </table>
</div><!-- FIM TABELA -->

{% endblock conteudo %}